version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - hhvm
  hhvm:
    image: potproject/hhvm-fpm
    volumes:
      - ./public/index.php:/var/www/public/index.php
      - ./public/.hhconfig:/var/www/public/.hhconfig